---
version: 0.2

phases:
  build:
    commands:
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python get-pip.py
      - pip install awscli
      - aws --version
      - curl -qL -o aws_credentials.json http://169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      - aws configure set region $AWS_REGION
      - aws configure set aws_access_key_id `./jq -r '.AccessKeyId' aws_credentials.json`
      - aws configure set aws_secret_access_key `./jq -r '.SecretAccessKey' aws_credentials.json`
      - aws configure set aws_session_token `./jq -r '.Token' aws_credentials.json`
      - yum -y install git
      - git submodule init
      - git submodule update
      - ls -alh submodules/quickstart-linux-bastion
      # Clean Up
      - rm -Rf .git jq get-pip.py aws_credentials.json
      - aws s3 sync . s3://solodev-quickstarts/eks/1.14 --delete
      - DATE=$(date +%d%H%M)
      - chmod 700 ci/bin/cleanStacks.sh ci/bin/stacks.sh
      # - ./bin/cleanStacks.sh
      - ./ci/bin/stacks.sh
      - echo "Cleanup!" | rm -f *json
  post_build:
    commands:
      - echo "S3 synced on `date`"