AWSTemplateFormatVersion: '2010-09-09'
Description: Solodev DCX for an existing kubernetes cluster

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "User Settings"
        Parameters: 
          - AdminUser
          - AdminPassword
      - 
        Label: 
          default: "Advanced Settings"
        Parameters: 
          - DatabaseName
          - DatabasePassword
          - AppSecret
      - 
        Label: 
          default: "EKS Cluster"
        Parameters: 
          - HelmLambdaArn
          - KubeConfigPath
          - KubeConfigKmsContext
          - ServiceRoleName

Parameters:

  AdminUser:
      Description: The solodev admin username
      Type: String
      Default: 'solodev'
      AllowedPattern: .+
      ConstraintDescription: Please set admin username

  AdminPassword: 
      NoEcho: true
      Description: The solodev admin password
      Type: String
      MinLength: 1
      MaxLength: 41
      AllowedPattern: .+
      ConstraintDescription: Please set admin password

  DatabaseName:
      Description: The solodev database name
      Type: String
      MinLength: 1
      MaxLength: 64
      AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
      ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
      Default: 'solodev'

  DatabasePassword:
      NoEcho: true
      Description: The database root password
      Type: String
      MinLength: 1
      MaxLength: 41
      AllowedPattern: .+
      ConstraintDescription: Please set database root password

  AppSecret:
    Type: String
    Description: Secret Key for App Encryption
    Default: 'c5d3adbb98f43thc0d12f0cc8fbcd7f8'

  HelmLambdaArn:
    Type: String

  KubeConfigPath:
    Type: String

  KubeConfigKmsContext:
    Type: String
    Default: "EKSQuickStart"

  ServiceRoleName:
    Type: String
    Default: 'aws-serviceaccount'

Resources:
  SolodevDCX:
    Type: "Custom::Helm"
    Version: '1.0'
    Properties:
      ServiceToken: !Ref HelmLambdaArn
      KubeConfigPath: !Ref KubeConfigPath
      KubeConfigKmsContext: !Ref KubeConfigKmsContext
      RepoUrl: https://raw.githubusercontent.com/techcto/charts/master/
      Chart: charts/solodev-dcx-aws
      Name: !Ref AWS::StackName
      Namespace: "solodev-dcx"
      ValueYaml: !Sub |
        env: prod
        serviceAccountName: "${ServiceRoleName}"
        storage:
          className: gp2
          size: 10G
        solodev:
          image:
            registry: 709373726912.dkr.ecr.us-east-1.amazonaws.com/0c908dc0-e52e-4d48-bf4c-9e883d405d92/cg-2469757812
            repository: solodev-cms
            tag: 9.1-latest
            pullPolicy: IfNotPresent
          port: 9000
          protocol: TCP
          storage:
            className: efs
            size: 10G
            mount: /var/www/solodev/clients/solodev
          settings:
            debug: false
            appSecret: ${AppSecret}
            appUser: ${AdminUser}
            appPassword: ${AdminPassword}
            dbHost: mysql
            dbName: ${DatabaseName}
            dbUser: solodev
            dbPassword: ${DatabasePassword}
            mongoDbName: solodev_views
        ui:
          image:
            registry: 709373726912.dkr.ecr.us-east-1.amazonaws.com/0c908dc0-e52e-4d48-bf4c-9e883d405d92/cg-2469757812
            repository: solodev-apache
            tag: 9.1-latest
            pullPolicy: IfNotPresent
          http:
            port: 80
            protocol: TCP
          https:
            port: 443
            protocol: TCP
        mysql:
          image:
            registry: 709373726912.dkr.ecr.us-east-1.amazonaws.com/0c908dc0-e52e-4d48-bf4c-9e883d405d92/cg-2469757812
            repository: mariadb
            tag: 9.1-latest
            pullPolicy: IfNotPresent
          port: 3306
          read:
            port: 3307
          settings:
        mongo:
          image:
            registry: 709373726912.dkr.ecr.us-east-1.amazonaws.com/0c908dc0-e52e-4d48-bf4c-9e883d405d92/cg-2469757812
            repository: techcto/mongo
            tag: 9.1-latest
            pullPolicy: IfNotPresent
          port: 27017
          settings:
            username: solodev
            password: ${DatabasePassword}
        redis:
          image:
            registry: 709373726912.dkr.ecr.us-east-1.amazonaws.com/0c908dc0-e52e-4d48-bf4c-9e883d405d92/cg-2469757812
            repository: redis
            tag: 9.1-latest
            pullPolicy: IfNotPresent
          port: 6379

Outputs:

    AdminUrl: 
        Description: Point your DNS to this CNAME.
        Value: "Locate external endpoint address for UI in services"
    AdminUsername: 
        Description: Solodev admin username.
        Value: !Ref AdminUser
    AdminPassword: 
        Description: Solodev admin password.
        Value: !Ref AdminPassword