AWSTemplateFormatVersion: '2010-09-09'
Description: Solodev DCX for an existing kubernetes cluster

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "User Settings"
        Parameters: 
          - AdminUser
          - AdminPassword
      - 
        Label: 
          default: "Advanced Settings"
        Parameters: 
          - DomainName
          - ClusterZone
          - DatabaseName
          - DatabasePassword
          - AppSecret
          - ClientId
          - ClientSecret
      - 
        Label: 
          default: "EKS Cluster"
        Parameters: 
          - HelmLambdaArn
          - KubeConfigPath
          - KubeConfigKmsContext

Parameters:
  DomainName:
    Description: This is the DNS Zone for all clusters
    Type: String

  ClusterZone:
    Description: This is the DNS Zone that for a single cluster
    Type: String

  AdminUser:
      Description: The solodev admin username
      Type: String
      Default: 'solodev'
      AllowedPattern: .+
      ConstraintDescription: Please set admin username

  AdminPassword: 
      NoEcho: true
      Description: The solodev admin password
      Type: String
      MinLength: 1
      MaxLength: 41
      AllowedPattern: .+
      ConstraintDescription: Please set admin password

  DatabaseName:
      Description: The solodev database name
      Type: String
      MinLength: 1
      MaxLength: 64
      AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
      ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
      Default: 'solodev'

  DatabasePassword:
      NoEcho: true
      Description: The database root password
      Type: String
      MinLength: 1
      MaxLength: 41
      AllowedPattern: .+
      ConstraintDescription: Please set database root password

  AppSecret:
    Type: String
    Description: Secret Key for App Encryption
    Default: 'c5d3adbb98f43thc0d12f0cc8fbcd7f8'

  HelmLambdaArn:
    Type: String

  KubeConfigPath:
    Type: String

  KubeConfigKmsContext:
    Type: String
    Default: "EKSQuickStart"

  StorageClass:
    Type: String
    Default: "ebs"

  ClientId:
    Type: String
    Default: ""
    
  ClientSecret:
    Type: String
    Default: ""

Resources:
  SolodevDCX:
    Type: "Custom::Helm"
    Version: '1.0'
    Properties:
      ServiceToken: !Ref HelmLambdaArn
      KubeConfigPath: !Ref KubeConfigPath
      KubeConfigKmsContext: !Ref KubeConfigKmsContext
      RepoUrl: https://raw.githubusercontent.com/techcto/charts/master/
      Chart: charts/solodev-dcx
      Name: !Ref AWS::StackName
      Namespace: "solodev-dcx"
      ValueYaml: !Sub |
        env: prod
        storage:
          size: 500M
          className: ${StorageClass}
        solodev:
          image:
            registry: docker.io
            repository: solodev/cms
            tag: latest
            pullPolicy: IfNotPresent
          domainName: ${DomainName}
          clusterZone: ${ClusterZone}
          port: 9000
          protocol: TCP
          storage:
            className: ${StorageClass}
            size: 5G
            mount: /var/www/solodev/clients/solodev
          settings:
            debug: false
            appSecret: ${AppSecret}
            appUser: ${AdminUser}
            appPassword: ${AdminPassword}
            dbHost: mysql
            dbName: ${DatabaseName}
            dbUser: solodev
            dbPassword: ${DatabasePassword}
            mongoDbName: solodev_views
            isISV: 'true'
            clientId: ${ClientId}
            clientSecret: ${ClientSecret}
          pullSecret: solodev
        ui:
          image:
            registry: docker.io
            repository: solodev/cms-apache
            tag: latest
            pullPolicy: IfNotPresent
          http:
            port: 80
            protocol: TCP
          https:
            port: 443
            protocol: TCP
        mysql:
          image:
            registry: docker.io
            repository: mariadb
            tag: 10.3
          port: 3306
          read:
            port: 3307
          settings:
        mongo:
          image:
            registry: docker.io
            repository: techcto/mongo
            tag: latest
            pullPolicy: IfNotPresent
          port: 27017
          settings:
            username: solodev
            password: ${DatabasePassword}
        redis:
          image:
            registry: docker.io
            repository: techcto/redis
            tag: latest
            pullPolicy: IfNotPresent
          port: 6379

Outputs:

    AdminUrl: 
        Description: Point your DNS to this CNAME.
        Value: !Join ["", [ !Ref "AWS::StackName", ".", !Ref ClusterZone ]]
    AdminUsername: 
        Description: Solodev admin username.
        Value: !Ref AdminUser
    AdminPassword: 
        Description: Solodev admin password.
        Value: !Ref AdminPassword