AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys an EKS cluster into an existing VPC
Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
  NodeAMIOS:
    AllowedValues:
      - Amazon-Linux-HVM
      - SUSE-SLES-15-HVM
    Default: Amazon-Linux-HVM
    Type: String
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    Default: aws-quickstart
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/.]*$
    Default: quickstart-amazon-eks/
    Type: String
  RemoteAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String
  AdditionalEKSAdminArns:
    Default: ""
    Type: CommaDelimitedList
  NodeInstanceType:
    Default: t3.medium
    Type: String
  NumberOfNodes:
    Default: 2
    Type: Number
  MaxNumberOfNodes:
    Default: 3
    Type: Number
  NodeGroupName:
    Default: Default
    Type: String
  NodeVolumeSize:
    Default: 20
    Type: String
  LambdaZipsBucketName:
    Type: String
    Default: ''
  VPCID:
    Type: "AWS::EC2::VPC::Id"
  PublicSubnet1ID:
    Type: "AWS::EC2::Subnet::Id"
  PublicSubnet2ID:
    Type: "AWS::EC2::Subnet::Id"
  PrivateSubnet1ID:
    Type: "AWS::EC2::Subnet::Id"
  PrivateSubnet2ID:
    Type: "AWS::EC2::Subnet::Id"
  KubernetesVersion:
    Type: String
    AllowedValues: [ "1.14", "1.13" ]
    Default: "1.14"
  ProvisionClusterAutoScaler:
    Type: String
    AllowedValues: [ "Enabled", "Disabled" ]
    Default: "Disabled"
  BootstrapArguments:
    Type: String
    Default: ""
  BastionOS:
    Type: String
    AllowedValues: [ "Amazon-Linux-HVM", "CentOS-7-HVM", "Ubuntu-Server-14.04-LTS-HVM", "Ubuntu-Server-16.04-LTS-HVM", "SUSE-SLES-15-HVM" ]
    Default: "Amazon-Linux-HVM"
  KubeConfigKmsContext:
    Type: String
    Default: "EKSQuickStart"
  ProvisionBastionHost:
    Type: String
    AllowedValues: [ "Enabled", "Disabled" ]
    Default: "Enabled"
  BastionBootstrapScript:
    Default: ""
    Type: String
  BastionInstanceType:
    Default: "t2.micro"
    Type: String
  BastionRootVolumeSize:
    Type: Number
    Default: 10
  BastionIAMRoleName:
    Type: String
    Default: ""
  BastionEnableTCPForwarding:
    Type: String
    Default: "false"
    AllowedValues: [ "true", "false" ]
  BastionEnableX11Forwarding:
    Type: String
    Default: "false"
    AllowedValues: [ "true", "false" ]
  BastionVariables:
    Type: String
    Default: ""
  EfsStorageClass:
    Type: String
    AllowedValues: [ Enabled, Disabled ]
    Default: Disabled
  EfsPerformanceMode:
    Type: String
    AllowedValues: [ generalPurpose, maxIO ]
    Default: generalPurpose
  EfsThroughputMode:
    Type: String
    AllowedValues: [ bursting, provisioned ]
    Default: bursting
  EfsProvisionedThroughputInMibps:
    Type: Number
    MinValue: 0
    Default: 0
  ProvisionSolodevDCXNetwork:
    Type: String
    AllowedValues: [ "Enabled", "Disabled" ]
    Default: "Disabled"
  ZoneName:
    Type: String
    Default: ""
  ZoneId:
    Type: String
    Default: ""
Conditions:
  CreateLambdaZipsBucket: !Equals [!Ref 'LambdaZipsBucketName', '']
  DefaultBastionBootstrap: !Equals [!Ref 'BastionBootstrapScript', '']
  EnableBastion: !Equals [!Ref 'ProvisionBastionHost', 'Enabled']
  CustomBastionRole: !Not [!Equals [!Ref 'BastionIAMRoleName', '']]
  AdditionalVars: !Not [!Equals [!Ref 'BastionVariables', '']]
  EnableClusterAutoScaler: !Equals [!Ref 'ProvisionClusterAutoScaler', 'Enabled']
  EnableEfs: !Equals [!Ref 'EfsStorageClass', 'Enabled']
  EnableSolodevDCXNetwork: !Equals [!Ref 'ProvisionSolodevDCXNetwork', 'Enabled']
Resources:
  BastionEksPermissions:
    Condition: EnableBastion
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "AllowEKSClusterOperations"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "eks:DescribeCluster"
              - "eks:DescribeUpdate"
              - "eks:ListUpdates"
              - "eks:UpdateClusterVersion"
            Resource: !Sub "arn:${AWS::Partition}:eks:${AWS::Region}:${AWS::AccountId}:cluster/${EKSControlPlane.EKSName}"
      Roles:
        - !If [CustomBastionRole, !Ref BastionIAMRoleName, !GetAtt IamStack.Outputs.BastionRole]
  BastionStack:
    Condition: EnableBastion
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/submodules/quickstart-linux-bastion/templates/linux-bastion.template'
      Parameters:
        VPCID: !Ref VPCID
        PublicSubnet1ID: !Ref PublicSubnet1ID
        PublicSubnet2ID: !Ref PublicSubnet2ID
        KeyPairName: !Ref KeyPairName
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        BastionInstanceType: !Ref BastionInstanceType
        RootVolumeSize: !Ref BastionRootVolumeSize
        AlternativeInitializationScript: !If
          - DefaultBastionBootstrap
          - !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}scripts/bastion_bootstrap.sh'
          - !Ref BastionBootstrapScript
        AlternativeIAMRole: !If [CustomBastionRole, !Ref BastionIAMRoleName, !GetAtt IamStack.Outputs.BastionRole]
        BastionAMIOS: !Ref BastionOS
        EnableTCPForwarding: !Ref BastionEnableTCPForwarding
        EnableX11Forwarding: !Ref BastionEnableX11Forwarding
        EnvironmentVariables: !Sub
        - >
          K8S_ROLE_ARN=${IamStack.Outputs.ControlPlaneProvisionRoleArn},
          K8S_CLUSTER_NAME=${EKSControlPlane.EKSName},
          DOMAIN=${ZoneName},
          K8S_CA_DATA=${EKSControlPlane.CAData},
          K8S_ENDPOINT=${EKSControlPlane.EKSEndpoint}${Joiner},
          ProvisionSolodevDCXNetwork=${ProvisionSolodevDCXNetwork}
          ${BastionVariables}
        - Joiner: !If [AdditionalVars, ",", ""]
  NodeGroupStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/amazon-eks-nodegroup.template.yaml'
      Parameters:
        KeyPairName: !Ref 'KeyPairName'
        NodeAMIOS: !Ref NodeAMIOS
        PrivateSubnet1ID: !Ref PrivateSubnet1ID
        PrivateSubnet2ID: !Ref PrivateSubnet2ID
        VPCID: !Ref VPCID
        NodeInstanceType: !Ref NodeInstanceType
        NumberOfNodes: !Ref NumberOfNodes
        MaxNumberOfNodes: !Ref MaxNumberOfNodes
        NodeGroupName: !Ref NodeGroupName
        NodeVolumeSize: !Ref NodeVolumeSize
        EKSControlPlane: !GetAtt EKSControlPlane.EKSName
        ControlPlaneSecurityGroup: !Ref ControlPlaneSecurityGroup
        NodeInstanceProfile: !GetAtt IamStack.Outputs.NodeInstanceProfile
        NodeInstanceRoleName: !GetAtt IamStack.Outputs.NodeInstanceRoleName
        KubernetesVersion: !Ref KubernetesVersion
        BootstrapArguments: !Ref BootstrapArguments
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
  BastionSShToNodes:
    Condition: EnableBastion
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      Description: Allow SSH from Bastion server to Nodes
      GroupId: !GetAtt NodeGroupStack.Outputs.EKSNodeSecurityGroup
      SourceSecurityGroupId: !GetAtt BastionStack.Outputs.BastionSecurityGroupID
      IpProtocol: tcp
      ToPort: 22
      FromPort: 22
  BastionToAPIServerAccess:
    Condition: EnableBastion
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      Description: Allow Bastion server to communicate with the cluster API Server
      GroupId: !Ref ControlPlaneSecurityGroup
      SourceSecurityGroupId: !GetAtt BastionStack.Outputs.BastionSecurityGroupID
      IpProtocol: tcp
      ToPort: 443
      FromPort: 443
  IamStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/amazon-eks-iam.template.yaml'
      Parameters:
        LambdaZipsBucketName: !If [ CreateLambdaZipsBucket, !Ref LambdaZipsBucket, !Ref LambdaZipsBucketName ]
        DeleteLambdaZipsBucketContents: !If [ CreateLambdaZipsBucket, "True", "False" ]
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        KubeConfigBucket: !Ref KubeConfigBucket
        AdditionalEKSAdminArns: !Join [ ",", !Ref AdditionalEKSAdminArns ]
        CreateBastionRole: !If [CustomBastionRole, "Disabled", !If [EnableBastion, "Enabled", "Disabled"]]
  FunctionStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/amazon-eks-functions.template.yaml'
      Parameters:
        LambdaZipsBucketName: !If [ CreateLambdaZipsBucket, !Ref LambdaZipsBucket, !Ref LambdaZipsBucketName ]
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        CopyZipsRoleArn: !GetAtt IamStack.Outputs.CopyZipsRoleArn
        EKSProvisionRoleArn: !GetAtt IamStack.Outputs.ControlPlaneProvisionRoleArn
        ControlPlaneSecurityGroup: !Ref ControlPlaneSecurityGroup
        EKSSubnetIds: !Sub "${PrivateSubnet1ID},${PrivateSubnet2ID}"
        DeleteBucketContentsRoleArn: !GetAtt IamStack.Outputs.DeleteBucketContentsRoleArn
        QuickStartStackMakerRoleArn: !GetAtt IamStack.Outputs.QuickStartStackMakerRoleArn
        DeleteLambdaZipsBucketContents: !If [ CreateLambdaZipsBucket, "True", "False" ]
        VPCID: !Ref VPCID
        KubeConfigUploadRoleArn: !GetAtt IamStack.Outputs.KubeConfigUploadRoleArn
        CleanupLoadBalancersRoleArn: !GetAtt IamStack.Outputs.CleanupLoadBalancersRoleArn
        CleanupSecurityGroupDependenciesRoleArn: !GetAtt IamStack.Outputs.CleanupSecurityGroupDependenciesRoleArn
        GetCallerArnRoleArn: !GetAtt IamStack.Outputs.GetCallerArnRoleArn
  ClusterAutoScalerStack:
    Condition: EnableClusterAutoScaler
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/amazon-eks-cluster-autoscaler.template.yaml'
      Parameters:
        HelmLambdaArn: !GetAtt FunctionStack.Outputs.HelmLambdaArn
        KubeConfigPath: !Sub "s3://${KubeConfigBucket}/.kube/config.enc"
        KubeConfigKmsContext: !Ref KubeConfigKmsContext
        NodeInstanceRoleName: !GetAtt IamStack.Outputs.NodeInstanceRoleName
        NodeAutoScalingGroup: !GetAtt NodeGroupStack.Outputs.NodeAutoScalingGroup
        EksClusterName: !GetAtt EKSControlPlane.EKSName
        KubernetesVersion: !Ref KubernetesVersion
  EfsStack:
    Condition: EnableEfs
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/amazon-eks-efs.template.yaml'
      Parameters:
        HelmLambdaArn: !GetAtt FunctionStack.Outputs.HelmLambdaArn
        KubeConfigPath: !Sub "s3://${KubeConfigBucket}/.kube/config.enc"
        KubeConfigKmsContext: !Ref KubeConfigKmsContext
        NodeGroupSecurityGroup: !GetAtt NodeGroupStack.Outputs.EKSNodeSecurityGroup
        PrivateSubnet1ID: !Ref PrivateSubnet1ID
        PrivateSubnet2ID: !Ref PrivateSubnet2ID
        PerformanceMode: !Ref EfsPerformanceMode
        ProvisionedThroughputInMibps: !Ref EfsProvisionedThroughputInMibps
        ThroughputMode: !Ref EfsThroughputMode
  LambdaZipsBucket:
    Type: AWS::S3::Bucket
    Condition: CreateLambdaZipsBucket
  DeleteBucketContents:
    Condition: CreateLambdaZipsBucket
    Type: Custom::DeleteBucketContents
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt 'FunctionStack.Outputs.DeleteBucketContentsLambdaArn'
      OutputBucket: !Ref 'LambdaZipsBucket'
  ControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Cluster communication
      VpcId: !Ref VPCID
  EKSControlPlane:
    Type: "Custom::CfnStackAssumeRole"
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt FunctionStack.Outputs.QuickStartStackMakerLambdaArn
      RoleArn: !GetAtt IamStack.Outputs.ControlPlaneProvisionRoleArn
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/amazon-eks-controlplane.template.yaml'
      ParentStackId: !Ref AWS::StackId
      CfnParameters:
        SecurityGroupIds: !Ref ControlPlaneSecurityGroup
        SubnetIds: !Join [",", [ !Ref PrivateSubnet1ID, !Ref PrivateSubnet2ID, !Ref PublicSubnet1ID, !Ref PublicSubnet2ID ]]
        RoleArn: !GetAtt IamStack.Outputs.ControlPlaneRoleArn
        NodeInstanceRoleArn: !GetAtt IamStack.Outputs.NodeInstanceRoleArn
        KubeManifestLambdaArn: !GetAtt FunctionStack.Outputs.KubeManifestLambdaArn
        KmsKeyArn: !GetAtt KmsKey.Arn
        KubeConfigUploadRoleArn: !GetAtt IamStack.Outputs.KubeConfigUploadRoleArn
        KubeConfigUploadLambdaArn: !GetAtt FunctionStack.Outputs.KubeConfigUploadLambdaArn
        KubeConfigS3Bucket: !Ref KubeConfigBucket
        AdditionalEKSAdminArns: !Join [ ",", !Ref AdditionalEKSAdminArns ]
        KubernetesVersion: !Ref KubernetesVersion
        KmsContext: !Ref KubeConfigKmsContext
        CleanupLoadBalancersLambdaArn: !GetAtt FunctionStack.Outputs.CleanupLoadBalancersLambdaArn
        GetCallerArnLambdaArn: !GetAtt FunctionStack.Outputs.GetCallerArnLambdaArn
        ControlPlaneProvisionRoleArn: !GetAtt IamStack.Outputs.ControlPlaneProvisionRoleArn
        ProvisionSolodevDCXNetwork: !Ref ProvisionSolodevDCXNetwork
  KmsKey:
    Type: "AWS::KMS::Key"
    Properties:
      KeyPolicy: {
        "Version": "2012-10-17",
        "Id": "key-default-1",
        "Statement": [
        {
          "Sid": "root access",
          "Effect": "Allow",
          "Principal": {"AWS": !Sub "arn:aws:iam::${AWS::AccountId}:root"},
          "Action": "kms:*",
          "Resource": "*"
        },
        {
          "Sid": "lambda encrypt",
          "Effect": "Allow",
          "Principal": {"AWS": !GetAtt IamStack.Outputs.KubeConfigUploadRoleArn},
          "Action": "kms:encrypt",
          "Resource": "*"
        },
        {
          "Sid": "lambda decrypt",
          "Effect": "Allow",
          "Principal": {"AWS": !GetAtt IamStack.Outputs.ControlPlaneProvisionRoleArn},
          "Action": "kms:decrypt",
          "Resource": "*"
        }
        ]
      }
  KubeConfigBucket:
    Type: "AWS::S3::Bucket"
Outputs:
  KubeConfigPath:
    Value: !Sub "s3://${KubeConfigBucket}/.kube/config.enc"
  HelmLambdaArn:
    Value: !GetAtt FunctionStack.Outputs.HelmLambdaArn
  KubeManifestLambdaArn:
    Value: !GetAtt FunctionStack.Outputs.KubeManifestLambdaArn
  KubeGetLambdaArn:
    Value: !GetAtt FunctionStack.Outputs.KubeGetLambdaArn
  BastionIP:
    Value: !If
      - EnableBastion
      - !GetAtt BastionStack.Outputs.EIP1
      - ""
  BastionSecurityGroup:
    Value: !If
      - EnableBastion
      - !GetAtt BastionStack.Outputs.BastionSecurityGroupID
      - ""
  BastionAutoScalingGroup:
    Value: !If
      - EnableBastion
      - !GetAtt BastionStack.Outputs.BastionAutoScalingGroup
      - ""
  EKSClusterName:
    Value: !GetAtt EKSControlPlane.EKSName
  NodeInstanceProfile:
    Value: !GetAtt IamStack.Outputs.NodeInstanceProfile
  NodeInstanceRoleName:
    Value: !GetAtt IamStack.Outputs.NodeInstanceRoleName
  ControlPlaneSecurityGroup:
    Value: !GetAtt ControlPlaneSecurityGroup.GroupId
  NodeGroupSecurityGroup:
    Value: !GetAtt NodeGroupStack.Outputs.EKSNodeSecurityGroup
  NodeInstanceRoleArn:
    Value: !GetAtt IamStack.Outputs.NodeInstanceRoleArn
  CleanupSecurityGroupDependenciesLambdaArn:
    Value: !GetAtt FunctionStack.Outputs.CleanupSecurityGroupDependenciesLambdaArn
