AWSTemplateFormatVersion: "2010-09-09"

Description: "Deploys the Solodev CMS helm chart into an existing kubernetes cluster (qs-1qde66ffn)"

Metadata: 

  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Cluster Settings"
        Parameters: 
          - ClusterName
          - WebStackArn
          - HelmLambdaArn
      - 
        Label: 
          default: "Optional: DNS"
        Parameters: 
          - DomainName
          - ClusterZone
      - 
        Label: 
          default: "User Settings"
        Parameters: 
          - AdminUser
          - AdminPassword
      - 
        Label: 
          default: "Advanced Settings"
        Parameters: 
          - DatabaseName
          - DatabasePassword
          - Namespace
          - AppSecret
          - ServiceRoleName
      - 
        Label: 
          default: "Helm Chart"
        Parameters: 
          - RepoUrl
          - Chart

Parameters:

  AdminUser:
      Description: The solodev admin username
      Type: String
      Default: 'solodev'
      AllowedPattern: .+
      ConstraintDescription: Please set admin username

  AdminPassword: 
      NoEcho: true
      Description: The solodev admin password
      Type: String
      MinLength: 1
      MaxLength: 41
      AllowedPattern: .+
      ConstraintDescription: Please set admin password

  DatabaseName:
      Description: The solodev database name
      Type: String
      MinLength: 1
      MaxLength: 64
      AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
      ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
      Default: 'solodev'

  DatabasePassword:
      NoEcho: true
      Description: The database root password
      Type: String
      MinLength: 1
      MaxLength: 41
      AllowedPattern: .+
      ConstraintDescription: Please set database root password

  AppSecret:
    Type: String
    Description: Secret Key for App Encryption
    Default: 'c5d3adbb98f43thc0d12f0cc8fbcd7f8'

  WebStackArn:
    Type: String

  HelmLambdaArn:
    Type: String

  ClusterName:
    Type: String

  ServiceRoleName:
    Type: String
    Default: "aws-serviceaccount"

  Namespace:
    Type: String
    Default: "solodev"

  RepoUrl:
    Type: String
    Default: "https://raw.githubusercontent.com/techcto/charts/master/"

  AppVersion:
    Type: String
    Default: "9.2.95"

  DomainName:
    Description: This is the DNS Zone for all clusters
    Type: String
    Default: ""

  ClusterZone:
    Description: This is the DNS Zone that for a single cluster
    Type: String
    Default: ""

  ClientId:
    Type: String
    Default: ""
    
  ClientSecret:
    Type: String
    Default: ""

  DefaultCMS:
    Type: String
    AllowedValues: [ "charts/solodev-cms-aws", "charts/wordpress" ]
    Default: "charts/wordpress"
    Description: "Choose preferred CMS"

Conditions:
  IsDefault: !Equals [!Ref DomainName, '']
  NotDefault:
      "Fn::Not":
        - Condition: IsDefault
  InstallSolodev: !Equals [!Ref DefaultCMS, 'charts/solodev-cms-aws']
  InstallWordpress: !Equals [!Ref DefaultCMS, 'charts/wordpress']

Resources:

  Marketplace:
    Type: "Custom::WebStack"
    Version: '1.0'
    Properties:
      ServiceToken: !Ref WebStackArn
      ClusterName: !Ref ClusterName
      Namespace: !Ref Namespace
      ServiceRoleName: !Ref ServiceRoleName
      Marketplace:
        Enable: "true"

  Wordpress:
    Condition: InstallWordpress
    DependsOn: Marketplace
    Type: "Custom::Helm"
    Version: '1.0'
    Properties:
      ServiceToken: !Ref HelmLambdaArn
      ClusterName: !Ref ClusterName
      RepoUrl: !Ref RepoUrl
      Chart: !Ref DefaultCMS
      Name: !Ref AWS::StackName
      Namespace: !Ref Namespace
      ValueYaml: !Sub |
        serviceAccountName: "${ServiceRoleName}"
        wordpress:
          image:
            registry: docker.io
            repository: solodev/wordpress
            tag: latest
            pullPolicy: IfNotPresent
          settings:
            appSecret: ${AppSecret}
            appUser: ${AdminUser}
            appPassword: ${AdminPassword}
            dbName: ${DatabaseName}
            dbPassword: ${DatabasePassword}
          domainName: ${DomainName}
          clusterZone: ${ClusterZone}

  SolodevCMS:
    Condition: InstallSolodev
    DependsOn: Marketplace
    Type: "Custom::Helm"
    Version: '1.0'
    Properties:
      ServiceToken: !Ref HelmLambdaArn
      ClusterName: !Ref ClusterName
      RepoUrl: !Ref RepoUrl
      Chart: !Ref DefaultCMS
      Name: !Ref AWS::StackName
      Namespace: !Ref Namespace
      ValueYaml: !Sub |
        serviceAccountName: "${ServiceRoleName}"
        solodev:
          image:
            registry: docker.io
            repository: solodev/cms
            tag: ${AppVersion}
            pullPolicy: IfNotPresent
          settings:
            appSecret: ${AppSecret}
            appUser: ${AdminUser}
            appPassword: ${AdminPassword}
            dbName: ${DatabaseName}
            dbPassword: ${DatabasePassword}
            clientId: ${ClientId}
            clientSecret: ${ClientSecret}
          pullSecret: solodev
          domainName: ${DomainName}
          clusterZone: ${ClusterZone}
        mongo:
          settings:
            password: ${DatabasePassword}

Outputs:

    AdminUrl: 
        Condition: NotDefault
        Description: Point your DNS to this CNAME.
        Value: !Join ["", [ !Ref "AWS::StackName", ".", !Ref ClusterZone ]]
    
    AdminUsername: 
        Description: Solodev admin username.
        Value: !Ref AdminUser
    
    AdminPassword: 
        Description: Solodev admin password.
        Value: !Ref AdminPassword
